# Generated by Django 3.0.4 on 2020-04-17 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('s_admin', '0003_restauranrtypemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantModel',
            fields=[
                ('res_id', models.IntegerField(primary_key=TabError, serialize=False)),
                ('res_name', models.CharField(max_length=40, unique=True)),
                ('res_contact', models.IntegerField(unique=True)),
                ('res_email', models.EmailField(max_length=254, unique=True)),
                ('res_password', models.CharField(max_length=30)),
                ('res_otp', models.IntegerField()),
                ('res_status', models.CharField(default=False, max_length=30)),
                ('res_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_admin.AreaModel')),
                ('res_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_admin.RestauranrTypeModel')),
            ],
        ),
    ]
